//! Tour generation types — the core schema for the Onboarding Ghost tour feature.
//!
//! `TourStop` is the final, narrated unit of a tour. `StopStub` is the
//! intermediate shape produced by `fetch_stop_documents` and consumed by
//! `narrate_stop`. `TourConfig` carries all runtime knobs; `Tour` is the
//! complete serialised artefact written to the two-level cache.

use serde::{Deserialize, Serialize};
use crate::git_mining::MiningWindow;
use crate::significance_ranking_types::RankingMeta;

/// Which heuristic(s) caused this commit to be selected for the tour.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TriggerKind {
    Revert,
    WasReverted,
    RepeatedFix,
    IncidentLinked,
    ArchitectureShaping,
}

/// The fully narrated unit that the frontend stop-viewer renders.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TourStop {
    /// 1-based ordering position within the tour.
    pub sequence: usize,
    pub commit_hash: String,
    /// ISO-8601 UTC timestamp from the original commit.
    pub timestamp_utc: String,
    /// Short title generated by the narration LLM (e.g. "The outage that added this check").
    pub title: String,
    /// 2-4 paragraph narrative body generated by the narration LLM.
    pub narration: String,
    /// Primary subsystem (first entry in `subsystems`).
    pub subsystem: String,
    /// All subsystems this commit touches (for cluster/co-occurrence views).
    pub subsystems: Vec<String>,
    /// Paths of files changed, for display.
    pub files_changed: Vec<String>,
    /// The heuristic(s) that triggered selection.
    pub triggered_by: Vec<TriggerKind>,
    /// Short rationale produced by the ranking step explaining why this commit was selected.
    pub selection_rationale: String,
    /// Linked document text (e.g. GitHub issue body, Jira description) if fetched.
    pub linked_document: Option<String>,
}

/// Intermediate shape: enough context for `narrate_stop` to build its prompt,
/// without requiring the full `CommitRecord` to cross the IPC boundary again.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StopStub {
    pub sequence: usize,
    pub commit_hash: String,
    pub timestamp_utc: String,
    /// Commit subject line.
    pub message_summary: String,
    pub subsystem: String,
    pub subsystems: Vec<String>,
    pub files_changed: Vec<String>,
    pub triggered_by: Vec<TriggerKind>,
    /// Rationale string from `RankedCandidate.rationale`.
    pub selection_rationale: String,
    /// Paraphrase-safe one-liner from `RankedCandidate.evidence_summary`.
    /// Used as cross-stop context in narration prompts (replaces title pre-pass).
    pub evidence_summary: String,
    /// Linked document text fetched by `fetch_stop_documents`, if any.
    pub linked_document: Option<String>,
}

/// The complete, persisted tour artefact. Written to the two-level cache at
/// `<cache_root>/tours/<cache_key>.json`. Individual stop narrations are also
/// written to `<cache_root>/narrations/<commit_hash>-<prompt_version>.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tour {
    pub repo_path: String,
    pub head_hash: String,
    pub window: MiningWindow,
    pub generated_at_utc: String,
    pub ranking_meta: RankingMeta,
    pub stops: Vec<TourStop>,
}

/// Runtime configuration for the narration step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TourConfig {
    pub narration_prompt_version: String,
    pub model_id: String,
    pub temperature: f32,
    pub max_narration_tokens: u32,
    /// If true, `fetch_stop_documents` will attempt to fetch linked issue/PR bodies.
    pub fetch_linked_documents: bool,
    pub github_token: Option<String>,
    /// GitHub "owner/repo" slug, provided manually. Never inferred from git remote.
    pub repo_slug: Option<String>,
    pub jira_base_url: Option<String>,
    pub jira_token: Option<String>,
}

impl Default for TourConfig {
    fn default() -> Self {
        Self {
            narration_prompt_version: "v1".into(),
            model_id: "gemini-1.5-pro".into(),
            temperature: 0.3,
            max_narration_tokens: 1024,
            fetch_linked_documents: false,
            github_token: None,
            repo_slug: None,
            jira_base_url: None,
            jira_token: None,
        }
    }
}
